### PR TITLE
Fix resolution of relative avatar urls for Gogs published in subpath

### LINKED ISSUE #1701: [gogs] Incorrect resolution of relative "avatar_url"
Drone is showing all broken images as avatars for repositories from Gogs source.
I've seen it's due to relative URLs being found in "avatar_url" element of the
``api/v1/orgs/orgname`` endpoint, for example:
``"avatar_url":"/gogs/avatars/6"``

Drone is turning that into an url relative to the Drone url, not the Gogs url.

### PR DESCRIPTION
**Pull request by strk**
Closes #1701
Includes a new test, and updates expected results for 3 of them 
(adding the schema part)

### CODE REVIEW

**Comment by strk** [comment]
NOTE: in its current state the patch fixes the display of "Available Repositories", but the "Active Repositories" tab still renders improperly resolved avatars for already-activated repositories.

Deleting active repositories and re-activating them fixes the issue.

File: remote/gogs/helper.go [hunk 1]
```diff
@@ -120,15 +120,23 @@ func fixMalformedAvatar(url string) string {
...
+// absolute url.
 func expandAvatar(repo, rawurl string) string {
-	if !strings.HasPrefix(rawurl, "/avatars/") {
+	aurl, err := url.Parse(rawurl)
+	if err != nil {
 		return rawurl
 	}
-	url, err := url.Parse(repo)
+	if aurl.IsAbs() {
+		// Url is already absolute
```
Comment (bradrydzewski) [inline remote/gogs/helper.go]: nice, didn't even know that helper existed!

**Comment by bradrydzewski** [comment]
thanks for adding the tests!
